import 'dotenv/config';
import cors from 'cors'; import express from 'express'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken';
import Patient from './models/Patient.js'; import Clinic from './models/Clinic.js'; import Visit from './models/Visit.js'; import Admin from './models/Admin.js'; import Subscription from './models/Subscription.js'; import Appointment from './models/Appointment.js'; import SystemConfig from './models/SystemConfig.js';
const app = express(); const port = Number(process.env.PORT) || 5000; const isVercel = process.env.VERCEL === '1';
// Keep one shared connection promise.  Serverless requests can arrive before
// Mongoose finishes connecting, so every API request waits for it explicitly.
let databaseReady = Promise.resolve();
app.use(cors()); app.use(express.json());
app.use('/api', async (_req, _res, next) => { try { await databaseReady; next(); } catch (error) { next(error); } });
const token = (admin) => jwt.sign({ id: admin._id, username: admin.username, name: admin.name, role: admin.role }, process.env.JWT_SECRET, { expiresIn: '12h' });
const auth = (req, res, next) => { try { const tokenStr = req.headers.authorization?.replace('Bearer ', ''); if (!tokenStr) return res.status(401).json({ message: 'يرجى تسجيل الدخول أولاً.' }); req.admin = jwt.verify(tokenStr, process.env.JWT_SECRET); next(); } catch (e) { if (res && typeof res.status === 'function') return res.status(401).json({ message: 'يرجى تسجيل الدخول أولاً.' }); next(e); } };
const developer = (req, res, next) => req.admin.role === 'developer' ? next() : res.status(403).json({ message: 'هذه الصفحة مخصصة للمطور فقط.' });
const allPermissions = ['patients', 'appointments', 'reports', 'finance', 'settings', 'medicalNotes'];
const requirePermission = (permission) => async (req, res, next) => { try { const account = await Admin.findById(req.admin.id).select('role username permissions'); if (!account) return res.status(401).json({ message: 'الحساب غير موجود.' }); const permissions = account.permissions?.length ? account.permissions : (account.username === 'drahmed' ? allPermissions : ['patients', 'appointments']); if (account.role === 'developer' || (account.role === 'doctor' && permission === 'medicalNotes') || permissions.includes(permission)) return next(); res.status(403).json({ message: 'ليس لديك صلاحية لهذه الصفحة.' }); } catch (error) { next(error); } };
app.post('/api/auth/login', async (req, res, next) => { try { const admin = await Admin.findOne({ username: req.body.username?.toLowerCase() }); if (!admin || !(await bcrypt.compare(req.body.password || '', admin.passwordHash))) return res.status(401).json({ message: 'اسم المستخدم أو كلمة المرور غير صحيحة.' }); res.json({ token: token(admin), admin: { username: admin.username, name: admin.name, role: admin.role, permissions: admin.permissions || [] } }); } catch (error) { next(error); } });
app.get('/api/auth/me', auth, (req, res) => res.json(req.admin)); app.get('/api/health', (_req, res) => res.json({ connected: mongoose.connection.readyState === 1 }));
app.get('/api/system', auth, async (_req, res, next) => { try { const config = await SystemConfig.findOne(); res.json({ clinicName: config?.clinicName || 'DocPoint' }); } catch (error) { next(error); } });
app.put('/api/developer/system', auth, developer, async (req, res, next) => { try { const config = await SystemConfig.findOneAndUpdate({}, { clinicName: req.body.clinicName?.trim() || 'DocPoint' }, { new: true, upsert: true }); res.json(config); } catch (error) { next(error); } });
app.get('/api/subscription', auth, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); res.json({ expiresAt: subscription?.expiresAt, active: Boolean(subscription && subscription.expiresAt > new Date()) }); } catch (error) { next(error); } });
app.post('/api/subscription/renew', auth, async (req, res, next) => { try { const subscription = await Subscription.findOne(); if (!subscription || !(await bcrypt.compare(req.body.code || '', subscription.renewalCodeHash))) return res.status(400).json({ message: 'كود التحقق غير صحيح.' }); const newCode = `CLINIC-${new Date().getFullYear() + 1}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; subscription.expiresAt = new Date(new Date().setMonth(new Date().getMonth() + 6)); subscription.renewedAt = new Date(); subscription.renewalCodeHash = await bcrypt.hash(newCode, 12); await subscription.save(); res.json({ expiresAt: subscription.expiresAt, nextCode: newCode }); } catch (error) { next(error); } });
app.get('/api/developer/subscription', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); res.json({ expiresAt: subscription?.expiresAt, renewedAt: subscription?.renewedAt, active: Boolean(subscription && subscription.expiresAt > new Date()) }); } catch (error) { next(error); } });
app.post('/api/developer/subscription/activate', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); subscription.expiresAt = new Date(new Date().setMonth(new Date().getMonth() + 6)); subscription.renewedAt = new Date(); await subscription.save(); res.json({ expiresAt: subscription.expiresAt, active: true }); } catch (error) { next(error); } });
app.post('/api/developer/subscription/stop', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); subscription.expiresAt = new Date(); await subscription.save(); res.json({ expiresAt: subscription.expiresAt, active: false }); } catch (error) { next(error); } });
app.post('/api/developer/subscription/code', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); const newCode = `CLINIC-${new Date().getFullYear() + 1}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; subscription.renewalCodeHash = await bcrypt.hash(newCode, 12); await subscription.save(); res.json({ code: newCode }); } catch (error) { next(error); } });
app.put('/api/developer/admins/:id/permissions', auth, developer, async (req, res, next) => { try { const allowed = ['patients', 'appointments', 'reports', 'finance', 'settings', 'medicalNotes']; const permissions = (req.body.permissions || []).filter((item) => allowed.includes(item)); const admin = await Admin.findByIdAndUpdate(req.params.id, { permissions }, { new: true }).select('username name role permissions'); if (!admin) return res.status(404).json({ message: 'الحساب غير موجود.' }); res.json(admin); } catch (error) { next(error); } });
app.use('/api', auth, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); if (!subscription || subscription.expiresAt <= new Date()) return res.status(402).json({ message: 'انتهى الاشتراك. يرجى تجديده للمتابعة.', code: 'SUBSCRIPTION_EXPIRED' }); next(); } catch (error) { next(error); } });
app.get('/api/admins', auth, requirePermission('settings'), async (req, res, next) => { try { const filter = req.admin.role === 'developer' ? {} : { $and: [{ role: { $ne: 'developer' } }, { username: { $ne: 'developer' } }] }; res.json(await Admin.find(filter).select('username name role permissions createdAt').sort({ createdAt: 1 })); } catch (error) { next(error); } });
app.post('/api/admins', auth, requirePermission('settings'), async (req, res, next) => { try { const passwordHash = await bcrypt.hash(req.body.password, 12); const admin = await Admin.create({ username: req.body.username, name: req.body.name, role: 'admin', passwordHash }); res.status(201).json({ _id: admin._id, username: admin.username, name: admin.name, role: admin.role, permissions: admin.permissions }); } catch (error) { next(error); } });
app.put('/api/admins/:id', auth, requirePermission('settings'), async (req, res, next) => { try { const existing = await Admin.findById(req.params.id); if (!existing || (existing.role === 'developer' && req.admin.role !== 'developer')) return res.status(404).json({ message: 'الحساب غير موجود.' }); if (existing.username === 'drahmed' && req.body.username !== 'drahmed') return res.status(403).json({ message: 'لا يمكن تغيير اسم مستخدم حساب د. أحمد.' }); const update = { name: req.body.name, username: req.body.username }; if (req.body.password) update.passwordHash = await bcrypt.hash(req.body.password, 12); const admin = await Admin.findByIdAndUpdate(req.params.id, update, { new: true, runValidators: true }).select('username name role permissions'); res.json(admin); } catch (error) { next(error); } });
app.delete('/api/admins/:id', auth, requirePermission('settings'), async (req, res, next) => { try { const admin = await Admin.findById(req.params.id); if (!admin || admin.role === 'developer') return res.status(404).json({ message: 'الحساب غير موجود.' }); if (admin.username === 'drahmed') return res.status(403).json({ message: 'لا يمكن حذف حساب د. أحمد.' }); await admin.deleteOne(); res.json({ message: 'تم حذف حساب الأدمن.' }); } catch (error) { next(error); } });
app.get('/api/appointments', auth, requirePermission('appointments'), async (req, res, next) => { try { const date = req.query.date ? new Date(`${req.query.date}T00:00:00`) : new Date(); const nextDay = new Date(date); nextDay.setDate(nextDay.getDate() + 1); const appointments = await Appointment.find({ scheduledAt: { $gte: date, $lt: nextDay }, status: { $in: ['محجوز', 'انتظار', 'دخل للطبيب'] } }).populate('patient', 'fullName phone').populate('clinic', 'name').sort({ scheduledAt: 1 }); res.json(appointments); } catch (error) { next(error); } });
app.post('/api/appointments', auth, requirePermission('appointments'), async (req, res, next) => { try { const scheduledAt = req.body.scheduledAt ? new Date(req.body.scheduledAt) : new Date(); const start = new Date(scheduledAt); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); const last = await Appointment.findOne({ scheduledAt: { $gte: start, $lt: end } }).sort({ queueNumber: -1 }).select('queueNumber'); const appointment = await Appointment.create({ ...req.body, scheduledAt, queueNumber: (last?.queueNumber || 0) + 1, createdBy: req.admin.id, status: 'محجوز' }); res.status(201).json(await appointment.populate(['patient', 'clinic'])); } catch (error) { next(error); } });
app.delete('/api/appointments/:id', auth, requirePermission('appointments'), async (req, res, next) => { try { const appointment = await Appointment.findByIdAndDelete(req.params.id); if (!appointment) return res.status(404).json({ message: 'الحجز غير موجود.' }); await Visit.deleteMany({ appointment: appointment._id, status: 'انتظار' }); res.json({ message: 'تم حذف الحجز نهائياً من قاعدة البيانات.' }); } catch (error) { next(error); } });
app.patch('/api/appointments/:id/attendance', auth, requirePermission('appointments'), async (req, res, next) => { try { const appointment = await Appointment.findById(req.params.id); if (!appointment) return res.status(404).json({ message: 'الحجز غير موجود.' }); if (appointment.status !== 'محجوز') return res.status(400).json({ message: 'تم تسجيل حضور هذه الحالة مسبقاً.' }); const { visitType = 'كشف', amount = 0, notes = '' } = req.body; appointment.status = 'انتظار'; appointment.visitType = visitType; appointment.amount = Number(amount) || 0; appointment.paymentStatus = 'محصل'; appointment.arrivedAt = new Date(); appointment.notes = notes; appointment.title = visitType === 'متابعة' ? 'متابعة' : 'كشف'; await appointment.save(); const visit = await Visit.create({ patient: appointment.patient, appointment: appointment._id, clinic: appointment.clinic, title: appointment.title, amount: appointment.amount, notes, status: 'انتظار', visitDate: appointment.arrivedAt, createdBy: req.admin.id }); res.json({ appointment, visit }); } catch (error) { next(error); } });
app.patch('/api/appointments/:id/status', auth, requirePermission('appointments'), async (req, res, next) => {
  try {
    const { status, notes } = req.body;
    if (!['دخل للطبيب', 'غادر', 'ملغى'].includes(status)) return res.status(400).json({ message: 'حالة غير صالحة.' });
    const appointment = await Appointment.findById(req.params.id);
    if (!appointment) return res.status(404).json({ message: 'الموعد غير موجود.' });

    if (status === 'غادر') {
      const visit = await Visit.findOneAndUpdate(
        { appointment: appointment._id },
        { $set: { status: 'مكتمل', notes: notes ?? appointment.notes, visitDate: new Date(), appointment: null } },
        { new: true }
      );
      if (!visit) return res.status(400).json({ message: 'لا يوجد كشف مكتمل مرتبط بهذا الموعد. سجّل حضور المريض أولاً.' });
      await Appointment.findByIdAndDelete(appointment._id);
      return res.json({ message: 'تم إنهاء الكشف وحذف الموعد من قاعدة البيانات.', visit });
    }

    if (status === 'دخل للطبيب') {
      appointment.status = status;
      appointment.enteredAt = new Date();
      if (notes !== undefined) appointment.notes = notes;
      await appointment.save();
      await Visit.findOneAndUpdate({ appointment: appointment._id }, { $set: { notes: appointment.notes, status: 'انتظار' } });
      return res.json(appointment);
    }

    await Visit.findOneAndUpdate({ appointment: appointment._id }, { $set: { status: 'ملغى' } });
    await Appointment.findByIdAndDelete(appointment._id);
    res.json({ message: 'تم إلغاء الموعد وحذفه من قاعدة البيانات.' });
  } catch (error) { next(error); }
});
app.get('/api/clinics', auth, async (_req, res, next) => { try { res.json(await Clinic.find({ active: true }).sort({ name: 1 })); } catch (error) { next(error); } });
app.post('/api/clinics', auth, requirePermission('settings'), async (req, res, next) => { try { res.status(201).json(await Clinic.create(req.body)); } catch (error) { next(error); } });
app.get('/api/patients', auth, async (req, res, next) => { try { const s = req.query.search?.trim(); const q = s ? { $or: [{ fullName: { $regex: s, $options: 'i' } }, { phone: { $regex: s, $options: 'i' } }, { nationalId: { $regex: s, $options: 'i' } }] } : {}; const patients = await Patient.find(q).populate('clinic', 'name location').populate('createdBy', 'name username').sort({ createdAt: -1 }).limit(100); const counts = await Visit.aggregate([{ $match: { patient: { $in: patients.map((patient) => patient._id) } } }, { $group: { _id: '$patient', count: { $sum: 1 } } }]); const countByPatient = new Map(counts.map((item) => [String(item._id), item.count])); res.json(patients.map((patient) => ({ ...patient.toObject(), visitsCount: countByPatient.get(String(patient._id)) || 0 }))); } catch (error) { next(error); } });
app.post('/api/patients', auth, requirePermission('patients'), async (req, res, next) => { try { const { initialFee, ...data } = req.body; const patient = await Patient.create({ ...data, createdBy: req.admin.id }); if (Number(initialFee) > 0) await Visit.create({ patient: patient._id, clinic: patient.clinic, title: 'كشف أولي', amount: Number(initialFee), notes: 'رسوم الكشف عند التسجيل.', createdBy: req.admin.id }); res.status(201).json(patient); } catch (error) { next(error); } });
app.get('/api/patients/:id', auth, async (req, res, next) => { try { const patient = await Patient.findById(req.params.id).populate('clinic', 'name location specialty').populate('createdBy', 'name username'); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); const [visits, bookings] = await Promise.all([Visit.find({ patient: patient._id }).populate('clinic', 'name').populate('createdBy', 'name username').sort({ visitDate: -1 }), Appointment.find({ patient: patient._id, status: 'محجوز' }).populate('clinic', 'name').sort({ scheduledAt: -1 })]); res.json({ patient, visits, bookings }); } catch (error) { next(error); } });
app.put('/api/patients/:id', auth, requirePermission('medicalNotes'), async (req, res, next) => { try { const patient = await Patient.findByIdAndUpdate(req.params.id, { medicalNotes: req.body.medicalNotes }, { new: true }); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); res.json(patient); } catch (error) { next(error); } });
app.put('/api/patients/:id/details', auth, requirePermission('patients'), async (req, res, next) => { try { const update = { fullName: req.body.fullName?.trim(), age: Number(req.body.age), gender: req.body.gender, nationality: req.body.nationality?.trim(), phone: req.body.phone?.trim(), clinic: req.body.clinic || undefined }; if (req.body.birthDate) update.birthDate = new Date(req.body.birthDate); if (req.body.nationalId?.trim()) update.nationalId = req.body.nationalId.trim(); const unset = {}; if (!req.body.birthDate) unset.birthDate = 1; if (!req.body.nationalId?.trim()) unset.nationalId = 1; const patient = await Patient.findByIdAndUpdate(req.params.id, { $set: update, ...(Object.keys(unset).length ? { $unset: unset } : {}) }, { new: true, runValidators: true }).populate('clinic', 'name location'); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); res.json(patient); } catch (error) { next(error); } });
app.post('/api/patients/:id/visits', auth, requirePermission('appointments'), async (req, res, next) => { try { const patient = await Patient.findById(req.params.id); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); const { title = 'كشف عيادة', amount = 0, notes = '', clinic, scheduledAt } = req.body; if (!clinic) return res.status(400).json({ message: 'يرجى اختيار العيادة.' }); const date = scheduledAt ? new Date(scheduledAt) : new Date(); if (Number.isNaN(date.getTime())) return res.status(400).json({ message: 'تاريخ الكشف غير صالح.' }); const appointment = await Appointment.create({ patient: patient._id, clinic, scheduledAt: date, notes, createdBy: req.admin.id, status: 'انتظار' }); try { const visit = await Visit.create({ patient: patient._id, appointment: appointment._id, clinic, title, amount: Number(amount) || 0, notes, status: 'انتظار', visitDate: date, createdBy: req.admin.id }); res.status(201).json({ appointment, visit }); } catch (visitError) { await Appointment.findByIdAndDelete(appointment._id); throw visitError; } } catch (error) { next(error); } });

app.put('/api/visits/:id', auth, requirePermission('medicalNotes'), async (req, res, next) => { try { const update = {}; if (typeof req.body.notes !== 'undefined') update.notes = req.body.notes; const visit = await Visit.findByIdAndUpdate(req.params.id, update, { new: true }); if (!visit) return res.status(404).json({ message: 'الزيارة غير موجودة.' }); res.json(visit); } catch (error) { next(error); } });
app.get('/api/dashboard', auth, requirePermission('finance'), async (_req, res, next) => { try { const [patients, visits, clinics, totals] = await Promise.all([Patient.countDocuments(), Visit.countDocuments({ status: 'مكتمل' }), Clinic.find({ active: true }).sort({ name: 1 }), Visit.aggregate([{ $match: { status: 'مكتمل' } }, { $group: { _id: '$clinic', income: { $sum: '$amount' }, visits: { $sum: 1 } } }])]); const map = new Map(totals.map((v) => [String(v._id), v])); const totalIncome = totals.reduce((sum, v) => sum + v.income, 0); res.json({ patients, visits, totalIncome, clinics: clinics.map((c) => ({ ...c.toObject(), income: map.get(String(c._id))?.income || 0, visits: map.get(String(c._id))?.visits || 0 })) }); } catch (error) { next(error); } });
app.get('/api/reports', auth, requirePermission('reports'), async (req, res, next) => { try { const match = { status: 'مكتمل' }; if (req.query.clinic) match.clinic = new mongoose.Types.ObjectId(req.query.clinic); if (req.query.from || req.query.to) { match.visitDate = {}; if (req.query.from) match.visitDate.$gte = new Date(`${req.query.from}T00:00:00`); if (req.query.to) match.visitDate.$lte = new Date(`${req.query.to}T23:59:59`); } const pipeline = [{ $match: match }, { $lookup: { from: 'patients', localField: 'patient', foreignField: '_id', as: 'patient' } }, { $unwind: '$patient' }]; if (req.query.nationality) pipeline.push({ $match: { 'patient.nationality': req.query.nationality } }); const [byClinic, summary, nationalities] = await Promise.all([Visit.aggregate([...pipeline, { $group: { _id: '$clinic', revenue: { $sum: '$amount' }, visitors: { $sum: 1 } } }]), Visit.aggregate([...pipeline, { $group: { _id: null, revenue: { $sum: '$amount' }, visitors: { $sum: 1 }, averagePayment: { $avg: '$amount' } } }]), Patient.distinct('nationality')]); const clinics = await Clinic.find({ active: true }); const map = new Map(byClinic.map((v) => [String(v._id), v])); res.json({ rows: clinics.map((c) => ({ id: c._id, name: c.name, location: c.location, revenue: map.get(String(c._id))?.revenue || 0, visitors: map.get(String(c._id))?.visitors || 0 })), summary: summary[0] || { revenue: 0, visitors: 0, averagePayment: 0 }, nationalities: nationalities.filter(Boolean) }); } catch (error) { next(error); } });
app.use((error, _req, res, next) => { if (error.code === 11000) { const field = Object.keys(error.keyPattern || {})[0]; return res.status(409).json({ message: field === 'nationalId' ? 'الرقم القومي مسجل بالفعل لمريض آخر.' : 'هذه البيانات مسجلة بالفعل.', field }); } if (error.name === 'ValidationError') return res.status(400).json({ message: 'يرجى مراجعة البيانات المدخلة.' }); console.error(error); res.status(500).json({ message: 'حدث خطأ في الخادم.' }); });
if (!process.env.MONGODB_URI || !process.env.JWT_SECRET) { console.error('أكمل MONGODB_URI و JWT_SECRET في .env'); process.exit(1); }
databaseReady = mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 })
  .then(async () => { if (!await Clinic.countDocuments()) await Clinic.insertMany([{ name: 'عيادة الأسنان', location: 'الفرع الرئيسي', specialty: 'طب الأسنان' }, { name: 'عيادة الأطفال', location: 'الفرع الرئيسي', specialty: 'طب الأطفال' }, { name: 'عيادة الباطنة', location: 'الفرع الرئيسي', specialty: 'باطنة عامة' }]); if (!await Admin.countDocuments()) { const passwordHash = await bcrypt.hash(process.env.ADMIN_SEED_PASSWORD || 'ChangeMeNow123!', 12); await Admin.insertMany([{ username: 'drahmed', name: 'د. أحمد', role: 'doctor', passwordHash, permissions: allPermissions }, { username: 'admin1', name: 'مدير العيادات', passwordHash }, { username: 'admin2', name: 'مدير الحسابات', passwordHash }, { username: 'admin3', name: 'مدير الاستقبال', passwordHash }]); } await Admin.updateOne({ username: 'drahmed', permissions: { $exists: false } }, { $set: { permissions: allPermissions } }); if (!await Admin.exists({ username: 'developer' })) await Admin.create({ username: 'developer', name: 'مطور النظام', role: 'developer', passwordHash: await bcrypt.hash(process.env.DEVELOPER_SEED_PASSWORD || 'DevClinic!2026', 12) }); if (!await Subscription.countDocuments()) await Subscription.create({ expiresAt: new Date('2026-08-22T18:05:00+03:00'), renewalCodeHash: await bcrypt.hash('CLINIC-2027-START', 12) }); })
  .catch((e) => { console.error(`تعذر الاتصال بـ MongoDB Atlas: ${e.message}`); if (!isVercel) process.exit(1); });
if (!isVercel) app.listen(port, '0.0.0.0', () => console.log(`الخادم المحلي يعمل على http://localhost:${port}`));

export default app;
