import 'dotenv/config';
import cors from 'cors'; import express from 'express'; import mongoose from 'mongoose'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken';
import Patient from './models/Patient.js'; import Clinic from './models/Clinic.js'; import Visit from './models/Visit.js'; import Admin from './models/Admin.js'; import Subscription from './models/Subscription.js';
const app = express(); const port = process.env.PORT || 5000;
app.use(cors()); app.use(express.json());
const token = (admin) => jwt.sign({ id: admin._id, username: admin.username, name: admin.name, role: admin.role }, process.env.JWT_SECRET, { expiresIn: '12h' });
const auth = (req, res, next) => { try { req.admin = jwt.verify(req.headers.authorization?.replace('Bearer ', ''), process.env.JWT_SECRET); next(); } catch { res.status(401).json({ message: 'يرجى تسجيل الدخول أولاً.' }); } };
const doctor = (req, res, next) => (req.admin.username === 'drahmed' || req.admin.role === 'developer') ? next() : res.status(403).json({ message: 'هذه الصلاحية للدكتور drahmed أو المطوّر فقط.' });
const developer = (req, res, next) => req.admin.role === 'developer' ? next() : res.status(403).json({ message: 'هذه الصفحة مخصصة للمطور فقط.' });
app.post('/api/auth/login', async (req, res, next) => { try { const admin = await Admin.findOne({ username: req.body.username?.toLowerCase() }); if (!admin || !(await bcrypt.compare(req.body.password || '', admin.passwordHash))) return res.status(401).json({ message: 'اسم المستخدم أو كلمة المرور غير صحيحة.' }); res.json({ token: token(admin), admin: { username: admin.username, name: admin.name, role: admin.role } }); } catch (error) { next(error); } });
app.get('/api/auth/me', auth, (req, res) => res.json(req.admin)); app.get('/api/health', (_req, res) => res.json({ connected: mongoose.connection.readyState === 1 }));
app.get('/api/subscription', auth, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); res.json({ expiresAt: subscription?.expiresAt, active: Boolean(subscription && subscription.expiresAt > new Date()) }); } catch (error) { next(error); } });
app.post('/api/subscription/renew', auth, async (req, res, next) => { try { const subscription = await Subscription.findOne(); if (!subscription || !(await bcrypt.compare(req.body.code || '', subscription.renewalCodeHash))) return res.status(400).json({ message: 'كود التحقق غير صحيح.' }); const newCode = `CLINIC-${new Date().getFullYear() + 1}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; subscription.expiresAt = new Date(new Date().setMonth(new Date().getMonth() + 6)); subscription.renewedAt = new Date(); subscription.renewalCodeHash = await bcrypt.hash(newCode, 12); await subscription.save(); res.json({ expiresAt: subscription.expiresAt, nextCode: newCode }); } catch (error) { next(error); } });
app.get('/api/developer/subscription', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); res.json({ expiresAt: subscription?.expiresAt, renewedAt: subscription?.renewedAt, active: Boolean(subscription && subscription.expiresAt > new Date()) }); } catch (error) { next(error); } });
app.post('/api/developer/subscription/activate', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); subscription.expiresAt = new Date(new Date().setMonth(new Date().getMonth() + 6)); subscription.renewedAt = new Date(); await subscription.save(); res.json({ expiresAt: subscription.expiresAt, active: true }); } catch (error) { next(error); } });
app.post('/api/developer/subscription/stop', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); subscription.expiresAt = new Date(); await subscription.save(); res.json({ expiresAt: subscription.expiresAt, active: false }); } catch (error) { next(error); } });
app.post('/api/developer/subscription/code', auth, developer, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); const newCode = `CLINIC-${new Date().getFullYear() + 1}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; subscription.renewalCodeHash = await bcrypt.hash(newCode, 12); await subscription.save(); res.json({ code: newCode }); } catch (error) { next(error); } });
app.use('/api', auth, async (_req, res, next) => { try { const subscription = await Subscription.findOne(); if (!subscription || subscription.expiresAt <= new Date()) return res.status(402).json({ message: 'انتهى الاشتراك. يرجى تجديده للمتابعة.', code: 'SUBSCRIPTION_EXPIRED' }); next(); } catch (error) { next(error); } });
app.get('/api/admins', auth, doctor, async (req, res, next) => { try { const filter = req.admin.role === 'developer' ? {} : { $and: [{ role: { $ne: 'developer' } }, { username: { $ne: 'developer' } }] }; res.json(await Admin.find(filter).select('username name role createdAt').sort({ createdAt: 1 })); } catch (error) { next(error); } });
app.post('/api/admins', auth, doctor, async (req, res, next) => { try { const passwordHash = await bcrypt.hash(req.body.password, 12); const admin = await Admin.create({ username: req.body.username, name: req.body.name, role: 'admin', passwordHash }); res.status(201).json({ _id: admin._id, username: admin.username, name: admin.name, role: admin.role }); } catch (error) { next(error); } });
app.put('/api/admins/:id', auth, doctor, async (req, res, next) => { try { const existing = await Admin.findById(req.params.id); if (!existing || (existing.role === 'developer' && req.admin.role !== 'developer')) return res.status(404).json({ message: 'الحساب غير موجود.' }); if (existing.username === 'drahmed' && req.body.username !== 'drahmed') return res.status(403).json({ message: 'لا يمكن تغيير اسم مستخدم حساب د. أحمد.' }); const update = { name: req.body.name, username: req.body.username }; if (req.body.password) update.passwordHash = await bcrypt.hash(req.body.password, 12); const admin = await Admin.findByIdAndUpdate(req.params.id, update, { new: true, runValidators: true }).select('username name role'); res.json(admin); } catch (error) { next(error); } });
app.delete('/api/admins/:id', auth, doctor, async (req, res, next) => { try { const admin = await Admin.findById(req.params.id); if (!admin || admin.role === 'developer') return res.status(404).json({ message: 'الحساب غير موجود.' }); if (admin.username === 'drahmed') return res.status(403).json({ message: 'لا يمكن حذف حساب د. أحمد.' }); await admin.deleteOne(); res.json({ message: 'تم حذف حساب الأدمن.' }); } catch (error) { next(error); } });
app.get('/api/clinics', auth, async (_req, res, next) => { try { res.json(await Clinic.find({ active: true }).sort({ name: 1 })); } catch (error) { next(error); } });
app.post('/api/clinics', auth, async (req, res, next) => { try { res.status(201).json(await Clinic.create(req.body)); } catch (error) { next(error); } });
app.get('/api/patients', auth, async (req, res, next) => { try { const s = req.query.search?.trim(); const q = s ? { $or: [{ fullName: { $regex: s, $options: 'i' } }, { phone: { $regex: s, $options: 'i' } }, { nationalId: { $regex: s, $options: 'i' } }] } : {}; res.json(await Patient.find(q).populate('clinic', 'name location').populate('createdBy', 'name username').sort({ createdAt: -1 }).limit(100)); } catch (error) { next(error); } });
app.post('/api/patients', auth, async (req, res, next) => { try { const { initialFee, ...data } = req.body; const patient = await Patient.create({ ...data, createdBy: req.admin.id }); if (Number(initialFee) > 0) await Visit.create({ patient: patient._id, clinic: patient.clinic, title: 'كشف أولي', amount: Number(initialFee), notes: 'رسوم الكشف عند التسجيل.', createdBy: req.admin.id }); res.status(201).json(patient); } catch (error) { next(error); } });
app.get('/api/patients/:id', auth, async (req, res, next) => { try { const patient = await Patient.findById(req.params.id).populate('clinic', 'name location specialty').populate('createdBy', 'name username'); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); const visits = await Visit.find({ patient: patient._id }).populate('clinic', 'name').populate('createdBy', 'name username').sort({ visitDate: -1 }); res.json({ patient, visits }); } catch (error) { next(error); } });
app.put('/api/patients/:id', auth, doctor, async (req, res, next) => { try { const patient = await Patient.findByIdAndUpdate(req.params.id, { medicalNotes: req.body.medicalNotes }, { new: true }); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); res.json(patient); } catch (error) { next(error); } });
app.post('/api/patients/:id/visits', auth, async (req, res, next) => { try { const patient = await Patient.findById(req.params.id); if (!patient) return res.status(404).json({ message: 'المريض غير موجود.' }); res.status(201).json(await Visit.create({ ...req.body, patient: patient._id, createdBy: req.admin.id })); } catch (error) { next(error); } });
app.get('/api/dashboard', auth, async (_req, res, next) => { try { const [patients, visits, clinics, totals] = await Promise.all([Patient.countDocuments(), Visit.countDocuments({ status: 'مكتمل' }), Clinic.find({ active: true }).sort({ name: 1 }), Visit.aggregate([{ $match: { status: 'مكتمل' } }, { $group: { _id: '$clinic', income: { $sum: '$amount' }, visits: { $sum: 1 } } }])]); const map = new Map(totals.map((v) => [String(v._id), v])); const totalIncome = totals.reduce((sum, v) => sum + v.income, 0); res.json({ patients, visits, totalIncome, clinics: clinics.map((c) => ({ ...c.toObject(), income: map.get(String(c._id))?.income || 0, visits: map.get(String(c._id))?.visits || 0 })) }); } catch (error) { next(error); } });
app.get('/api/reports', auth, async (req, res, next) => { try { const match = { status: 'مكتمل' }; if (req.query.clinic) match.clinic = new mongoose.Types.ObjectId(req.query.clinic); if (req.query.from || req.query.to) { match.visitDate = {}; if (req.query.from) match.visitDate.$gte = new Date(`${req.query.from}T00:00:00`); if (req.query.to) match.visitDate.$lte = new Date(`${req.query.to}T23:59:59`); } const pipeline = [{ $match: match }, { $lookup: { from: 'patients', localField: 'patient', foreignField: '_id', as: 'patient' } }, { $unwind: '$patient' }]; if (req.query.nationality) pipeline.push({ $match: { 'patient.nationality': req.query.nationality } }); const [byClinic, summary, nationalities] = await Promise.all([Visit.aggregate([...pipeline, { $group: { _id: '$clinic', revenue: { $sum: '$amount' }, visitors: { $sum: 1 } } }]), Visit.aggregate([...pipeline, { $group: { _id: null, revenue: { $sum: '$amount' }, visitors: { $sum: 1 }, averagePayment: { $avg: '$amount' } } }]), Patient.distinct('nationality')]); const clinics = await Clinic.find({ active: true }); const map = new Map(byClinic.map((v) => [String(v._id), v])); res.json({ rows: clinics.map((c) => ({ id: c._id, name: c.name, location: c.location, revenue: map.get(String(c._id))?.revenue || 0, visitors: map.get(String(c._id))?.visitors || 0 })), summary: summary[0] || { revenue: 0, visitors: 0, averagePayment: 0 }, nationalities: nationalities.filter(Boolean) }); } catch (error) { next(error); } });
app.use((error, _req, res) => { if (error.code === 11000) { const field = Object.keys(error.keyPattern || {})[0]; return res.status(409).json({ message: field === 'nationalId' ? 'الرقم القومي مسجل بالفعل لمريض آخر.' : 'هذه البيانات مسجلة بالفعل.', field }); } if (error.name === 'ValidationError') return res.status(400).json({ message: 'يرجى مراجعة البيانات المدخلة.' }); console.error(error); res.status(500).json({ message: 'حدث خطأ في الخادم.' }); });
if (!process.env.MONGODB_URI || !process.env.JWT_SECRET) { console.error('أكمل MONGODB_URI و JWT_SECRET في .env'); process.exit(1); }
mongoose.connect(process.env.MONGODB_URI, { serverSelectionTimeoutMS: 10000 })
  .then(async () => { if (!await Clinic.countDocuments()) await Clinic.insertMany([{ name: 'عيادة الأسنان', location: 'الفرع الرئيسي', specialty: 'طب الأسنان' }, { name: 'عيادة الأطفال', location: 'الفرع الرئيسي', specialty: 'طب الأطفال' }, { name: 'عيادة الباطنة', location: 'الفرع الرئيسي', specialty: 'باطنة عامة' }]); if (!await Admin.countDocuments()) { const passwordHash = await bcrypt.hash(process.env.ADMIN_SEED_PASSWORD || 'ChangeMeNow123!', 12); await Admin.insertMany([{ username: 'drahmed', name: 'د. أحمد', role: 'doctor', passwordHash }, { username: 'admin1', name: 'مدير العيادات', passwordHash }, { username: 'admin2', name: 'مدير الحسابات', passwordHash }, { username: 'admin3', name: 'مدير الاستقبال', passwordHash }]); } if (!await Admin.exists({ username: 'developer' })) await Admin.create({ username: 'developer', name: 'مطور النظام', role: 'developer', passwordHash: await bcrypt.hash(process.env.DEVELOPER_SEED_PASSWORD || 'DevClinic!2026', 12) }); if (!await Subscription.countDocuments()) await Subscription.create({ expiresAt: new Date('2026-08-22T18:05:00+03:00'), renewalCodeHash: await bcrypt.hash('CLINIC-2027-START', 12) }); if (!process.env.VERCEL) app.listen(port, () => console.log(`API running at http://localhost:${port}`)); })
  .catch((e) => { console.error(`تعذر الاتصال بـ MongoDB Atlas: ${e.message}`); if (!process.env.VERCEL) process.exit(1); });

export default app;
